"""mig1

Revision ID: 42137d0d6f98
Revises: 
Create Date: 2026-03-09 12:57:49.684136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42137d0d6f98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('courses')
    # ### end Alembic commands ###
